name: my_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  
  #my dependencies -------------------------------------------------------------------
  flutter_dotenv: ^5.0.0
  firebase_core: ^2.27.0
  firebase_core_web: ^2.13.0
  cloud_firestore: ^4.15.10
  firebase_auth: ^4.17.8
  firebase_storage: ^11.6.5
  fluttertoast: ^8.2.4
  image_picker: ^1.0.7
  logging: ^1.0.0
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  http: ^1.0.0
  google_sign_in: ^6.2.1
  web: ^0.5.1
  googleapis: ^13.1.0
  googleapis_auth: ^1.5.1
  url_launcher: ^6.2.5
  flutter_alarm_clock: ^0.1.1
  alarm: ^3.0.14
  socket_io_client: ^2.0.0
  intl: ^0.18.1
  provider: ^6.0.5
  path_provider: ^2.1.2
  flutter_local_notifications: ^17.0.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.7.0
  flame_splash_screen: ^0.3.0
  carousel_slider: ^4.2.1
  kommunicate_flutter: ^1.9.0
  #my dependencies ---------------------------------------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Urbanist
      fonts:
        - asset: fonts/Urbanist-VariableFont_wght.ttf
          weight: 700
    - family: PilatExtended  
      fonts:
        - asset: fonts/PilatExtended-Regular.ttf
        - asset: fonts/PilatExtended-Bold.ttf
          weight: 600


    - family: Inter
      fonts:
      - asset: fonts/Inter-VariableFont_slnt,wght.ttf


  assets:
    - .env
    - pictures/profile.png
    - pictures/adeen.png
    - pictures/essa.png
    - pictures/mehdi.png
    - pictures/hurraira.png
    - pictures/mustafa.png
    - pictures/my_app_logo.png
    - pictures/google-icon.png
    - audios/alarm.mp3
    - pictures/






 