// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUDBxQA4HLd2QMFFCRkCqEJJjAQOX_Qms',
    appId: '1:12273615091:android:708e599cc2f80bb4d37786',
    messagingSenderId: '12273615091',
    projectId: 'ideaenhancerapp',
    storageBucket: 'ideaenhancerapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf1_0krc9MRTWu1RkVYHDd_nERZmGozQs',
    appId: '1:12273615091:ios:60e978edde99ed58d37786',
    messagingSenderId: '12273615091',
    projectId: 'ideaenhancerapp',
    storageBucket: 'ideaenhancerapp.appspot.com',
    androidClientId:
        '12273615091-otnldh67r8kbm5q3tdpcnc7askjq8ps7.apps.googleusercontent.com',
    iosClientId:
        '12273615091-98mp6u2iuqii5sohda2imbek48gr0aeq.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
